[package]
name = "barkbin_frontend"
version = "0.1.0"
authors = ["Pascal Hartig <phartig@rdrei.net>"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"
barkbin_backend = { version = "0.1.0", path = "../backend" }
barkbin_common = { version = "0.1.0", path = "../common" }
